// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetEchoOKCode is the HTTP code returned for type GetEchoOK
const GetEchoOKCode int = 200

/*GetEchoOK get echo o k

swagger:response getEchoOK
*/
type GetEchoOK struct {
}

// NewGetEchoOK creates GetEchoOK with default headers values
func NewGetEchoOK() *GetEchoOK {

	return &GetEchoOK{}
}

// WriteResponse to the client
func (o *GetEchoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetEchoBadRequestCode is the HTTP code returned for type GetEchoBadRequest
const GetEchoBadRequestCode int = 400

/*GetEchoBadRequest get echo bad request

swagger:response getEchoBadRequest
*/
type GetEchoBadRequest struct {
}

// NewGetEchoBadRequest creates GetEchoBadRequest with default headers values
func NewGetEchoBadRequest() *GetEchoBadRequest {

	return &GetEchoBadRequest{}
}

// WriteResponse to the client
func (o *GetEchoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
