// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEchoHandlerFunc turns a function with the right signature into a get echo handler
type GetEchoHandlerFunc func(GetEchoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEchoHandlerFunc) Handle(params GetEchoParams) middleware.Responder {
	return fn(params)
}

// GetEchoHandler interface for that can handle valid get echo params
type GetEchoHandler interface {
	Handle(GetEchoParams) middleware.Responder
}

// NewGetEcho creates a new http.Handler for the get echo operation
func NewGetEcho(ctx *middleware.Context, handler GetEchoHandler) *GetEcho {
	return &GetEcho{Context: ctx, Handler: handler}
}

/*GetEcho swagger:route GET /echo getEcho

echo name

echo name

*/
type GetEcho struct {
	Context *middleware.Context
	Handler GetEchoHandler
}

func (o *GetEcho) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEchoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
