swagger: "2.0"
basePath: /api/v1
schemes:
- http
consumes:
- application/json
produces:
- application/json
info:
  description: "example"
  version: "1.0.0"
  title: "example"
paths:
  "/echo":
    get:
      deprecated: false
      summary: echo name
      description: "echo name"
      responses:
        200:
          $ref: "#/definitions/GenericResp"
        400:
          $ref: "#/definitions/GenericResp"
    post:
      deprecated: false
      parameters:
      - name: body
        in: body
        schema:
          $ref: "#/definitions/Item"
      responses:
        200:
          $ref: "#/definitions/GenericResp"
        400:
          $ref: "#/definitions/GenericResp"
  "/echo/{name}":
    get:
      deprecated: false
      parameters:
      - type: string
        name: name
        in: path
        required: true
      - type: integer
        format: int64
        in: query
        name: page
        required: false
      - type: integer
        format: int64
        in: query
        name: pagesize
        required: false
        default: 10
      responses:
        200:
          $ref: "#/definitions/GenericResp"
        400:
          $ref: "#/definitions/GenericResp"
    post:
      deprecated: false
      parameters:
      - type: string
        name: name
        in: path
        required: true
      - name: body
        in: body
        schema:
          $ref: "#/definitions/Item"
      responses:
        200:
          $ref: "#/definitions/GenericResp"
        400:
          $ref: "#/definitions/GenericResp"
definitions:
  Item:
    type: object
    properties:
      name:
        type: string
  Foo:
    type: object
    required:
      - "name"
    properties:
      name:
        type: string
      type:
        type: string
        description: "负载类型"
        enum:
          - "Deployment"
          - "DaemonSet"
          - "StatefulSet"
      labels:
        $ref: "#/definitions/Labels"
      isadmin:
        type: boolean
  Labels:
    type: object
    additionalProperties:
      type: string
  GenericResp:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      data:
        type: object